### ISSUE TITLE
Are migrations 

### ISSUE THREAD

**Issue by doodlydroll** [henryjw/knex-db2#16]
Are migrations supported by knex-db2?

I am trying to apply migrations but get following error
`Exception has occurred: TypeError
TypeError: Cannot read property 'apply' of undefined
    at SchemaCompiler.toSQL (/home/adk/src/easyviz/easyviz-backend/node_modules/knex/lib/schema/compiler.js:50:26)
    at SchemaBuilder.toSQL (/home/adk/src/easyviz/easyviz-backend/node_modules/knex/lib/schema/builder.js:68:43)
    at /home/adk/src/easyviz/easyviz-backend/node_modules/knex/lib/runner.js:37:34
    at tryCatcher (/home/adk/src/easyviz/easyviz-backend/node_modules/bluebird/js/release/util.js:16:23)
    at /home/adk/src/easyviz/easyviz-backend/node_modules/bluebird/js/release/using.js:185:26`

Here is the line from compiler.js:50:
 `   this[query.method].apply(this, query.args);`

where query.method is "hasTable" and query.args is "knex_migrations".

**Comment by henryjw** [comment]
Thanks for the feedback. Unfortunately, migrations are not supported at the moment, but I'm adding this to my list of things to implement for the next release (hopefully in the next week or two).

**Comment by doodlydroll** [comment]
Awesome. I'll be happy to test :)

**Comment by henryjw** [comment]
@doodlydroll I haven't had time to implement this, but it's still at the top of my priority list for this project.

**Comment by doodlydroll** [comment]
Hi @henryjw. No worries. I wish I could help.I am also tight on time.
